services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: obrador_db
      MYSQL_USER: obrador_user
      MYSQL_PASSWORD: obrador_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: sh -c "until mysqladmin ping -h db -uroot -proot_password --skip-ssl; do echo 'Esperando a la base de datos...'; sleep 2; done; python manage.py migrate && python populate_data.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:Z
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=obrador_db
      - DB_USER=obrador_user
      - DB_PASSWORD=obrador_password
      - DB_HOST=db
      - DB_PORT=3306
      - CONTACT_EMAIL=sbohjes2104@fp.iesromerovargas.com
      - RESEND_API_KEY=re_eWcF81HT_2hJhjYrjqNMQYRyebozY9CB1
      - RESEND_FROM_EMAIL=Artesanía en cada bocado <onboarding@resend.dev>

    depends_on:
      - db

volumes:
  db_data:
