# Generated by Django 4.2.30 on 2026-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_producto_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, help_text='Ruta de la imagen o clase CSS del icono', max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='shop.alergeno'),
        ),
    ]
