# Generated by Django 4.2.30 on 2026-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alergeno_producto_descripcion_producto_alergenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dia_recogida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
