# Generated by Django 4.2.30 on 2026-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reseña',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='puntuacion',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
